//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: newprotoData/proto/mmo3d_activity_task.proto
namespace protos
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Activity_Task")]
  public partial class Activity_Task : global::ProtoBuf.IExtensible
  {
    public Activity_Task() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _describe = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"describe", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string describe
    {
      get { return _describe; }
      set { _describe = value; }
    }
    private uint _function_id = (uint)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"function_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint function_id
    {
      get { return _function_id; }
      set { _function_id = value; }
    }
    private uint _type = (uint)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _week = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(6, Name=@"week", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> week
    {
      get { return _week; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _open_time = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(7, Name=@"open_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> open_time
    {
      get { return _open_time; }
    }
  
    private uint _mode = (uint)0;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint mode
    {
      get { return _mode; }
      set { _mode = value; }
    }
    private uint _teamSize = (uint)0;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"teamSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint teamSize
    {
      get { return _teamSize; }
      set { _teamSize = value; }
    }
    private uint _label = (uint)0;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"label", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint label
    {
      get { return _label; }
      set { _label = value; }
    }
    private uint _limit_team = (uint)0;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"limit_team", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint limit_team
    {
      get { return _limit_team; }
      set { _limit_team = value; }
    }
    private string _limit_des = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"limit_des", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string limit_des
    {
      get { return _limit_des; }
      set { _limit_des = value; }
    }
    private uint _appear_lv = (uint)0;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"appear_lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint appear_lv
    {
      get { return _appear_lv; }
      set { _appear_lv = value; }
    }
    private uint _lv_limit = (uint)0;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"lv_limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint lv_limit
    {
      get { return _lv_limit; }
      set { _lv_limit = value; }
    }
    private uint _is_country = (uint)0;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"is_country", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint is_country
    {
      get { return _is_country; }
      set { _is_country = value; }
    }
    private uint _times = (uint)0;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint times
    {
      get { return _times; }
      set { _times = value; }
    }
    private uint _activity = (uint)0;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"activity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint activity
    {
      get { return _activity; }
      set { _activity = value; }
    }
    private uint _unlock_id = (uint)0;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"unlock_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint unlock_id
    {
      get { return _unlock_id; }
      set { _unlock_id = value; }
    }
    private string _ui_name = "";
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"ui_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ui_name
    {
      get { return _ui_name; }
      set { _ui_name = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _task_id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(20, Name=@"task_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> task_id
    {
      get { return _task_id; }
    }
  
    private string _icon = "";
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private string _icon1 = "";
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"icon1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string icon1
    {
      get { return _icon1; }
      set { _icon1 = value; }
    }
    private uint _notice_limit = (uint)0;
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"notice_limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint notice_limit
    {
      get { return _notice_limit; }
      set { _notice_limit = value; }
    }
    private string _open_icon = "";
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"open_icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string open_icon
    {
      get { return _open_icon; }
      set { _open_icon = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _remind_time = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(25, Name=@"remind_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> remind_time
    {
      get { return _remind_time; }
    }
  
    private string _time_text1 = "";
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"time_text1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string time_text1
    {
      get { return _time_text1; }
      set { _time_text1 = value; }
    }
    private string _time_text2 = "";
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"time_text2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string time_text2
    {
      get { return _time_text2; }
      set { _time_text2 = value; }
    }
    private string _time_text3 = "";
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"time_text3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string time_text3
    {
      get { return _time_text3; }
      set { _time_text3 = value; }
    }
    private string _time_text4 = "";
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"time_text4", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string time_text4
    {
      get { return _time_text4; }
      set { _time_text4 = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _decorative_describe = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(30, Name=@"decorative_describe", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> decorative_describe
    {
      get { return _decorative_describe; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _start_describe = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(31, Name=@"start_describe", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> start_describe
    {
      get { return _start_describe; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _start_inform = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(32, Name=@"start_inform", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> start_inform
    {
      get { return _start_inform; }
    }
  
    private uint _drop = (uint)0;
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"drop", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint drop
    {
      get { return _drop; }
      set { _drop = value; }
    }
    private uint _dropview = (uint)0;
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"dropview", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint dropview
    {
      get { return _dropview; }
      set { _dropview = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _reward_type = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(35, Name=@"reward_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> reward_type
    {
      get { return _reward_type; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _reward_id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(36, Name=@"reward_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> reward_id
    {
      get { return _reward_id; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _reward_num = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(37, Name=@"reward_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> reward_num
    {
      get { return _reward_num; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _picture = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(38, Name=@"picture", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> picture
    {
      get { return _picture; }
    }
  
    private string _target = "";
    [global::ProtoBuf.ProtoMember(39, IsRequired = false, Name=@"target", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string target
    {
      get { return _target; }
      set { _target = value; }
    }
    private uint _ready_time = (uint)0;
    [global::ProtoBuf.ProtoMember(40, IsRequired = false, Name=@"ready_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint ready_time
    {
      get { return _ready_time; }
      set { _ready_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Activity_Task_ARRAY")]
  public partial class Activity_Task_ARRAY : global::ProtoBuf.IExtensible
  {
    public Activity_Task_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<protos.Activity_Task> _items = new global::System.Collections.Generic.List<protos.Activity_Task>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protos.Activity_Task> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}