//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: newprotoData/proto/mmo3d_activity_reward.proto
namespace protos
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Activity_Reward")]
  public partial class Activity_Reward : global::ProtoBuf.IExtensible
  {
    public Activity_Reward() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _type = (uint)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _order_number = (uint)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"order_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint order_number
    {
      get { return _order_number; }
      set { _order_number = value; }
    }
    private uint _activity = (uint)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"activity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint activity
    {
      get { return _activity; }
      set { _activity = value; }
    }
    private uint _drop = (uint)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"drop", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint drop
    {
      get { return _drop; }
      set { _drop = value; }
    }
    private uint _dropview = (uint)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"dropview", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint dropview
    {
      get { return _dropview; }
      set { _dropview = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _reward_type = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(7, Name=@"reward_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> reward_type
    {
      get { return _reward_type; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _reward_id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(8, Name=@"reward_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> reward_id
    {
      get { return _reward_id; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _reward_num = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(9, Name=@"reward_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> reward_num
    {
      get { return _reward_num; }
    }
  
    private string _icon = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private string _icon_empty = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"icon_empty", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string icon_empty
    {
      get { return _icon_empty; }
      set { _icon_empty = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Activity_Reward_ARRAY")]
  public partial class Activity_Reward_ARRAY : global::ProtoBuf.IExtensible
  {
    public Activity_Reward_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<protos.Activity_Reward> _items = new global::System.Collections.Generic.List<protos.Activity_Reward>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protos.Activity_Reward> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}